all:
	@cd hello;make
	@cd storageTest;make
	@cd libsess;make
	@cd libfs;make
	@cd libcrypt;make

clean:
	@cd hello;make clean
	@cd storageTest;make clean
	@cd libsess;make clean
	@cd libfs;make clean
	@cd libcrypt;make clean
