set(CMAKE_SYSTEM_NAME Linux)

set(CMAKE_CROSSCOMPILING TRUE)

set(CMAKE_CXX_COMPILER ${CMAKE_CURRENT_SOURCE_DIR}/../optee/3.6/toolchains/aarch64/bin/aarch64-linux-gnu-g++)

set(CMAKE_C_COMPILER ${CMAKE_CURRENT_SOURCE_DIR}/../optee/3.6/toolchains/aarch64/bin/aarch64-linux-gnu-gcc)

set(CMAKE_FIND_ROOT_PATH ${CMAKE_CURRENT_SOURCE_DIR}/../optee/3.6/toolchains/aarch64/)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)

set(THREADS_PTHREAD_ARG ${CMAKE_CURRENT_SOURCE_DIR}/../optee/3.6/toolchains/aarch64/)
