all:
	@cd hello;make
	@cd storage;make
	@cd storage2;make
	@cd aes_perf;make
	@cd concurrent;make
	@cd concurrent_large;make

clean:
	@cd hello;make clean
	@cd storage;make clean
	@cd storage2;make clean
	@cd aes_perf;make clean
	@cd concurrent;make clean
	@cd concurrent_large;make clean
