all:
	@cd hello;make
	@cd storage;make
	@cd storage2;make
	@cd aes_perf;make
	@cd concurrent;make
	@cd concurrent_large;make
	@cd create_fail_test;make
	@cd crypt;make
	@cd os_test_lib;make
	@cd os_test;make
	@cd sims_keepalive;make
	@cd sims;make
	@cd rpc_test;make
	@cd sdp_basic;make
	@cd sha_perf;make
	@cd socket;make
	@cd storage_benchmark;make

clean:
	@cd hello;make clean
	@cd storage;make clean
	@cd storage2;make clean
	@cd aes_perf;make clean
	@cd concurrent;make clean
	@cd concurrent_large;make clean
	@cd create_fail_test;make clean
	@cd crypt;make clean
	@cd os_test_lib;make clean
	@cd os_test;make clean
	@cd sims_keepalive;make clean
	@cd sims;make clean
	@cd rpc_test;make clean
	@cd sdp_basic;make clean
	@cd sha_perf;make clean
	@cd socket;make clean
	@cd storage_benchmark;make clean
